version: '3.8'

services:

  service:
    build:
      context: .
      dockerfile: Dockerfile
    image: service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/JavaCode
      - SPRING_DATASOURCE_USERNAME=java
      - SPRING_DATASOURCE_PASSWORD=java

  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=JavaCode
      - POSTGRES_USER=java
      - POSTGRES_PASSWORD=java
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis
    command: --port 6379
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: